BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[resources] (
    [id] NVARCHAR(1000) NOT NULL,
    [content] NVARCHAR(4000) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [resources_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [updated_at] DATETIME2 NOT NULL,
    CONSTRAINT [resources_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
